name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: windows-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v3

        # Install Flutter command
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.10.0'
            channel: 'stable'
            

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --release
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          run: |
            npm install -g firebase-tools
            firebase deploy --only hosting:portfolio-7349e --token ${{ secrets.FIREBASE_TOKEN }}
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./